version: "3.8"

services:
  spark-master:
    image: bde2020/spark-master:3.3.0-hadoop3.3
    container_name: spark-master
    ports:
      - 8081:8080
      - 7077:7077
    environment:
      - INIT_DAEMON_STEP=setup_spark
    networks:
      - shopnet
  spark-worker-1:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - 8082:8081
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    networks:
      - shopnet
  spark-worker-2:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - 8083:8081
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    networks:
      - shopnet
  sparkapp:
    image: sparkapp
    environment:
      - PRODUCTION=True
      - SOCKET_IP=0.0.0.0
      - SOCKET_PORT=9090
      - SPARKAPP_IP=sparkapp
      - DATABASE_IP=storedb
    depends_on:
      [ spark-master, spark-worker-1, spark-worker-2, migrationStoreDB, migration ]
    ports:
      - 5004:5004
    networks:
      - shopnet
  authenticationDB:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: [ "CMD-SHELL", "for i in {1..3}; do mysqladmin ping -h localhost -u root -proot && sleep 6 || exit 1; done" ]
      start_period: 40s
      retries: 25
      timeout: 25s
    networks:
      - authnet
    volumes:
      - authvol:/var/lib/mysql
  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - authnet
      - shopnet
  authentication:
    image: authentication
    environment:
      - PRODUCTION=True
      - DATABASE_URL=authenticationDB
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
    ports:
      - 5000:5000
    depends_on:
      migration:
        condition: service_completed_successfully
    networks:
      - authnet
  migration:
    image: migration
    environment:
      - PRODUCTION=True
      - DATABASE_URL=authenticationDB
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
    depends_on:
      authenticationDB:
        condition: service_healthy
    networks:
      - authnet
  storedb:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: [ "CMD-SHELL", "for i in {1..3}; do mysqladmin ping -h localhost -u root -proot && sleep 6 || exit 1; done" ]
      start_period: 40s
      retries: 25
      timeout: 25s
    networks:
      - shopnet
    volumes:
      - shopvol:/var/lib/mysql
  storeOwner:
    image: owner_application
    environment:
      - PRODUCTION=True
      - DATABASE_URL=storedb
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
      - BLOCKCHAIN_URL=blockchain
    ports:
      - 5001:5001
    depends_on:
      migrationStoreDB:
        condition: service_completed_successfully
    networks:
      - shopnet
  migrationStoreDB:
    image: migration_storedb
    environment:
      - PRODUCTION=True
      - DATABASE_URL=storedb
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
    depends_on:
      storedb:
        condition: service_healthy
    networks:
      - shopnet
  storeCustomer:
    image: customer_store
    environment:
      - PRODUCTION=True
      - DATABASE_URL=storedb
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
      - BLOCKCHAIN_URL=blockchain
    ports:
      - 5002:5002
    depends_on:
      migrationStoreDB:
        condition: service_completed_successfully
    networks:
      - shopnet
  storeCourier:
    image: courier_store
    environment:
      - PRODUCTION=True
      - DATABASE_URL=storedb
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
      - BLOCKCHAIN_URL=blockchain
    ports:
      - 5003:5003
    depends_on:
      migrationStoreDB:
        condition: service_completed_successfully
    networks:
      - shopnet
  blockchain:
    image: trufflesuite/ganache-cli
    ports:
      - 8545:8545
    networks:
      - shopnet


volumes:
  authvol:
  shopvol:

networks:
  authnet:
  shopnet:



