version: "3.8"

services:
  authenticationDB:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD-SHELL", "for i in {1..3}; do mysqladmin ping -h localhost -u root -proot && sleep 6 || exit 1; done" ]
      start_period: 40s
      retries: 25
      timeout: 25s
  adminer:
    image: adminer
    ports:
      - 8083:8080
  authentication:
    image: authentication
    environment:
      - PRODUCTION=True
      - DATABASE_URL=authenticationDB
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
    ports:
      - 5000:5000
    depends_on:
      migration:
        condition: service_completed_successfully
  migration:
    image: migration
    environment:
      - PRODUCTION=True
      - DATABASE_URL=authenticationDB
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
    depends_on:
      authenticationDB:
        condition: service_healthy
  storedb:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3307:3306
    healthcheck:
      test: [ "CMD-SHELL", "for i in {1..3}; do mysqladmin ping -h localhost -u root -proot && sleep 6 || exit 1; done" ]
      start_period: 40s
      retries: 25
      timeout: 25s
  storeOwner:
    image: owner_application
    environment:
      - PRODUCTION=True
      - DATABASE_URL=storedb
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
    ports:
      - 5001:5001
    depends_on:
      migrationStoreDB:
        condition: service_completed_successfully
  migrationStoreDB:
    image: migration_storedb
    environment:
      - PRODUCTION=True
      - DATABASE_URL=storedb
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
    depends_on:
      storedb:
        condition: service_healthy
  storeCustomer:
    image: customer_store
    environment:
      - PRODUCTION=True
      - DATABASE_URL=storedb
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
    ports:
      - 5002:5002
    depends_on:
      migrationStoreDB:
        condition: service_completed_successfully
  storeCourier:
    image: courier_store
    environment:
      - PRODUCTION=True
      - DATABASE_URL=storedb
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
    ports:
      - 5003:5003
    depends_on:
      migrationStoreDB:
        condition: service_completed_successfully



